# Libraries

In [1]:
import numpy as np

In [2]:
!conda install numpy

Channels:
 - defaults
Platform: linux-64
Solving environment: done

# All requested packages already installed.



# Create Array

In [3]:
egg_box = np.array(['chicken_egg', 'country_egg', 'quail_egg'])

In [4]:
egg_box

array(['chicken_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [5]:
egg_box.shape

(3,)

In [6]:
egg_box.ndim

1

# Array dimensions (0-d, 1-d, 2-d, 3d)

In [7]:
egg_box_zero = np.array('egg')

In [8]:
egg_box_zero.ndim

0

In [9]:
egg_box_zero.shape

()

In [10]:
egg_box_two = np.array([['chicken_egg', 'country_egg', 'quail_egg'],['chicken_egg', 'country_egg', 'quail_egg']])

In [11]:
egg_box_two

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

In [12]:
egg_box_3 = np.array([[['chicken_egg', 'country_egg', 'quail_egg'],['chicken_egg', 'country_egg', 'quail_egg']], 
                      [['chicken_egg', 'country_egg', 'quail_egg'],['chicken_egg', 'country_egg', 'quail_egg']]])

In [13]:
egg_box_3

array([[['chicken_egg', 'country_egg', 'quail_egg'],
        ['chicken_egg', 'country_egg', 'quail_egg']],

       [['chicken_egg', 'country_egg', 'quail_egg'],
        ['chicken_egg', 'country_egg', 'quail_egg']]], dtype='<U11')

In [14]:
egg_box_two.ndim

2

In [15]:
egg_box_two.shape

(2, 3)

In [16]:
egg_box_3.shape

(2, 2, 3)

# Array operations (statistics methods, arithmetic, logical, expo, sqrt, sine)

In [17]:
a = np.array([1,2,3])
a^2

array([3, 0, 1])

In [18]:
np.std(a)

0.816496580927726

In [19]:
array =  np.array([1,2,3])


# Compute the statistical values
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

Mean: 2.0
Median: 2.0
Standard Deviation: 0.816496580927726
Variance: 0.6666666666666666


In [20]:
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original matrix:")
print(matrix)

# Compute the determinant
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

# Compute the inverse
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

Original matrix:
[[ 9  9  9]
 [ 5  6 10]
 [ 4  7  7]]
Determinant: -108.00000000000003
Inverse:
[[ 0.25925926  0.         -0.33333333]
 [-0.0462963  -0.25        0.41666667]
 [-0.10185185  0.25       -0.08333333]]


In [21]:
array1 = np.random.randint(1, 11, size=(3, 4))
array2 = np.random.randint(1, 11, size=(3, 4))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)

Array 1:
[[ 2  2  7  5]
 [ 1  1  9  3]
 [ 2  8 10  2]]
Array 2:
[[10  2  2  5]
 [ 5  6  4  6]
 [ 2 10  1  3]]
Element-wise addition:
[[12  4  9 10]
 [ 6  7 13  9]
 [ 4 18 11  5]]
Element-wise subtraction:
[[-8  0  5  0]
 [-4 -5  5 -3]
 [ 0 -2  9 -1]]
Element-wise multiplication:
[[20  4 14 25]
 [ 5  6 36 18]
 [ 4 80 10  6]]
Element-wise division:
[[ 0.2         1.          3.5         1.        ]
 [ 0.2         0.16666667  2.25        0.5       ]
 [ 1.          0.8        10.          0.66666667]]


# Array modification

In [22]:
egg_box

array(['chicken_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [23]:
egg_box_two

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

### numpy.insert(arr, obj, values, axis=None)

In [24]:
np.insert(egg_box, 1, 'duck_egg')

array(['chicken_egg', 'duck_egg', 'country_egg', 'quail_egg'],
      dtype='<U11')

In [25]:
np.insert(egg_box_two, 1, 'duck_egg', axis=1)

array([['chicken_egg', 'duck_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'duck_egg', 'country_egg', 'quail_egg']],
      dtype='<U11')

In [26]:
np.insert(egg_box_two, 2, 'dinosaur_egg')

array(['chicken_egg', 'country_egg', 'dinosaur_eg', 'quail_egg',
       'chicken_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [27]:
np.insert(egg_box_two, 1, 'dino_egg', axis=0)

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['dino_egg', 'dino_egg', 'dino_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

### numpy.delete(arr, obj, axis=None)[source]

In [28]:
egg_box_copy = np.delete(egg_box, 2)

In [29]:
egg_box

array(['chicken_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [30]:
egg_box

array(['chicken_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [31]:
egg_box_copy

array(['chicken_egg', 'country_egg'], dtype='<U11')

### numpy.append(arr, values, axis=None)

In [32]:
egg_box

array(['chicken_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [33]:
egg_box_two

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

In [34]:
np.append(egg_box, 'duck_egg')

array(['chicken_egg', 'country_egg', 'quail_egg', 'duck_egg'],
      dtype='<U11')

# Access array elements (Indexing, slicing)

In [35]:
egg_box 

array(['chicken_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [36]:
egg_box_two

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

In [37]:
egg_box_3

array([[['chicken_egg', 'country_egg', 'quail_egg'],
        ['chicken_egg', 'country_egg', 'quail_egg']],

       [['chicken_egg', 'country_egg', 'quail_egg'],
        ['chicken_egg', 'country_egg', 'quail_egg']]], dtype='<U11')

In [38]:
egg_box[-3]

'chicken_egg'

In [39]:
egg_box_two[1,1]

'country_egg'

In [40]:
egg_box_3[1,1,2]

'quail_egg'

## array[start : stop: step]

In [41]:
egg_box

array(['chicken_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [42]:
egg_box_two

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

In [43]:
egg_box[0:10:2]

array(['chicken_egg', 'quail_egg'], dtype='<U11')

In [44]:
egg_box_two[0:1]

array([['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

# Array reshape

### 1d to 2d

In [45]:
egg_box = np.append(egg_box, 'duck_egg')

In [46]:
egg_box.shape

(4,)

In [47]:
egg_box.reshape(2,2)

array([['chicken_egg', 'country_egg'],
       ['quail_egg', 'duck_egg']], dtype='<U11')

### 1d to 3d

In [48]:
# egg_box.reshape(2,2,2)

In [49]:
egg_box = np.array(['chicken_egg', 'country_egg', 'quail_egg', 'duck_egg', 'chicken_egg', 'country_egg', 'quail_egg', 'duck_egg'])

# Array iteration

In [50]:
egg_box 

array(['chicken_egg', 'country_egg', 'quail_egg', 'duck_egg',
       'chicken_egg', 'country_egg', 'quail_egg', 'duck_egg'],
      dtype='<U11')

In [51]:
egg_box_two

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

In [52]:
for i in egg_box:
    print("I am ", i)

I am  chicken_egg
I am  country_egg
I am  quail_egg
I am  duck_egg
I am  chicken_egg
I am  country_egg
I am  quail_egg
I am  duck_egg


In [53]:
for i in egg_box_two:
    for j in i:
        print("I am ", j)

I am  chicken_egg
I am  country_egg
I am  quail_egg
I am  chicken_egg
I am  country_egg
I am  quail_egg


In [54]:
for i in np.nditer(egg_box_two):
    print("I am ", i)

I am  chicken_egg
I am  country_egg
I am  quail_egg
I am  chicken_egg
I am  country_egg
I am  quail_egg


In [55]:
for idx, i in np.ndenumerate(egg_box_two):
    print("index", idx)
    print("I am ", i)

index (0, 0)
I am  chicken_egg
index (0, 1)
I am  country_egg
index (0, 2)
I am  quail_egg
index (1, 0)
I am  chicken_egg
index (1, 1)
I am  country_egg
index (1, 2)
I am  quail_egg


# Array joining

In [56]:
egg_box_two

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

In [57]:
egg_box_new = np.array([['egg1', 'egg2', 'egg3'],['egg4', 'egg5', 'egg6']])

In [58]:
egg_box_new

array([['egg1', 'egg2', 'egg3'],
       ['egg4', 'egg5', 'egg6']], dtype='<U4')

### hstack - row

In [59]:
np.hstack((egg_box_two, egg_box_new))

array([['chicken_egg', 'country_egg', 'quail_egg', 'egg1', 'egg2',
        'egg3'],
       ['chicken_egg', 'country_egg', 'quail_egg', 'egg4', 'egg5',
        'egg6']], dtype='<U11')

### vstack - column

In [60]:
np.vstack((egg_box_two, egg_box_new))

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg'],
       ['egg1', 'egg2', 'egg3'],
       ['egg4', 'egg5', 'egg6']], dtype='<U11')

### dstack

In [61]:
np.dstack((egg_box_two, egg_box_new))

array([[['chicken_egg', 'egg1'],
        ['country_egg', 'egg2'],
        ['quail_egg', 'egg3']],

       [['chicken_egg', 'egg4'],
        ['country_egg', 'egg5'],
        ['quail_egg', 'egg6']]], dtype='<U11')

# Array splitting

In [62]:
egg_box

array(['chicken_egg', 'country_egg', 'quail_egg', 'duck_egg',
       'chicken_egg', 'country_egg', 'quail_egg', 'duck_egg'],
      dtype='<U11')

In [63]:
np.array_split(egg_box, 4)

[array(['chicken_egg', 'country_egg'], dtype='<U11'),
 array(['quail_egg', 'duck_egg'], dtype='<U11'),
 array(['chicken_egg', 'country_egg'], dtype='<U11'),
 array(['quail_egg', 'duck_egg'], dtype='<U11')]

#### hsplit(), vsplit(), dsplit() are also there

# Copy vs view

In [64]:
egg_box_copy = egg_box.copy()
egg_box_view = egg_box.view()

In [65]:
egg_box_copy

array(['chicken_egg', 'country_egg', 'quail_egg', 'duck_egg',
       'chicken_egg', 'country_egg', 'quail_egg', 'duck_egg'],
      dtype='<U11')

In [66]:
egg_box

array(['chicken_egg', 'country_egg', 'quail_egg', 'duck_egg',
       'chicken_egg', 'country_egg', 'quail_egg', 'duck_egg'],
      dtype='<U11')

In [67]:
egg_box_view[0] = 'duck_egg'

In [68]:
egg_box_view

array(['duck_egg', 'country_egg', 'quail_egg', 'duck_egg', 'chicken_egg',
       'country_egg', 'quail_egg', 'duck_egg'], dtype='<U11')

In [69]:
egg_box

array(['duck_egg', 'country_egg', 'quail_egg', 'duck_egg', 'chicken_egg',
       'country_egg', 'quail_egg', 'duck_egg'], dtype='<U11')

In [70]:
egg_box_copy[1] = 'dino_egg'

In [71]:
egg_box

array(['duck_egg', 'country_egg', 'quail_egg', 'duck_egg', 'chicken_egg',
       'country_egg', 'quail_egg', 'duck_egg'], dtype='<U11')

In [72]:
my_list = [1,2,3,4,5]
my_list + 1

TypeError: can only concatenate list (not "int") to list

In [ ]:
my_array = np.array([1,2,3,4,5])
my_array+1