# Libraries

In [1]:
import numpy as np

In [2]:
!conda install numpy

Channels:
 - defaults
Platform: linux-64
Solving environment: done

# All requested packages already installed.



# Create Array

In [3]:
egg_box = np.array(['chicken_egg', 'country_egg', 'quail_egg', 'ostriches_egg'])

In [4]:
egg_box

array(['chicken_egg', 'country_egg', 'quail_egg', 'ostriches_egg'],
      dtype='<U13')

In [48]:
egg_box.shape

(5,)

In [49]:
egg_box.ndim

1

# Array dimensions (0-d, 1-d, 2-d, 3d)

In [50]:
egg_box_zero = np.array('egg1')

In [51]:
egg_box_zero.ndim

0

In [9]:
egg_box_zero.shape

()

In [10]:
egg_box_two = np.array([['chicken_egg', 'country_egg', 'quail_egg'],['chicken_egg', 'country_egg', 'quail_egg']])

In [11]:
egg_box_two

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

In [12]:
egg_box_3 = np.array([[['chicken_egg', 'country_egg', 'quail_egg'],['chicken_egg', 'country_egg', 'quail_egg']], 
                      [['chicken_egg', 'country_egg', 'quail_egg'],['chicken_egg', 'country_egg', 'quail_egg']]])

In [13]:
egg_box_3

array([[['chicken_egg', 'country_egg', 'quail_egg'],
        ['chicken_egg', 'country_egg', 'quail_egg']],

       [['chicken_egg', 'country_egg', 'quail_egg'],
        ['chicken_egg', 'country_egg', 'quail_egg']]], dtype='<U11')

In [14]:
egg_box_two.ndim

2

In [15]:
egg_box_two.shape

(2, 3)

In [16]:
egg_box_3.shape

(2, 2, 3)

# Array operations (statistics methods, arithmetic, logical, expo, sqrt, sine)

In [17]:
a = np.array([1,2,3])
a^2

array([3, 0, 1])

In [18]:
np.std(a)

0.816496580927726

In [19]:
array =  np.array([1,2,3])


# Compute the statistical values
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

Mean: 2.0
Median: 2.0
Standard Deviation: 0.816496580927726
Variance: 0.6666666666666666


In [20]:
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original matrix:")
print(matrix)

# Compute the determinant
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

# Compute the inverse
inverse = np.linalg.inv(matrix)
print("Inverse:")
print(inverse)

Original matrix:
[[10  4  9]
 [ 3  3  5]
 [ 3 10  1]]
Determinant: -233.0000000000001
Inverse:
[[ 0.20171674 -0.36909871  0.03004292]
 [-0.05150215  0.07296137  0.09871245]
 [-0.09012876  0.3776824  -0.07725322]]


In [21]:
array1 = np.random.randint(1, 11, size=(3, 4))
array2 = np.random.randint(1, 11, size=(3, 4))
print("Array 1:")
print(array1)
print("Array 2:")
print(array2)

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)

Array 1:
[[ 6  9 10  6]
 [ 4  3  4  3]
 [ 8  2  1  1]]
Array 2:
[[ 1  6  6  3]
 [ 1  1  1 10]
 [ 7  9  4  1]]
Element-wise addition:
[[ 7 15 16  9]
 [ 5  4  5 13]
 [15 11  5  2]]
Element-wise subtraction:
[[ 5  3  4  3]
 [ 3  2  3 -7]
 [ 1 -7 -3  0]]
Element-wise multiplication:
[[ 6 54 60 18]
 [ 4  3  4 30]
 [56 18  4  1]]
Element-wise division:
[[6.         1.5        1.66666667 2.        ]
 [4.         3.         4.         0.3       ]
 [1.14285714 0.22222222 0.25       1.        ]]


# Array modification

In [22]:
egg_box

array(['chicken_egg', 'country_egg', 'quail_egg', 'ostriches_egg'],
      dtype='<U13')

In [23]:
egg_box_two

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

### numpy.insert(arr, obj, values, axis=None)

In [24]:
np.insert(egg_box, 1, 'duck_egg')

array(['chicken_egg', 'duck_egg', 'country_egg', 'quail_egg',
       'ostriches_egg'], dtype='<U13')

In [25]:
np.insert(egg_box_two, 1, 'duck_egg', axis=1)

array([['chicken_egg', 'duck_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'duck_egg', 'country_egg', 'quail_egg']],
      dtype='<U11')

In [26]:
np.insert(egg_box_two, 2, 'dinosaur_egg')

array(['chicken_egg', 'country_egg', 'dinosaur_eg', 'quail_egg',
       'chicken_egg', 'country_egg', 'quail_egg'], dtype='<U11')

In [27]:
np.insert(egg_box_two, 1, 'dino_egg', axis=0)

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['dino_egg', 'dino_egg', 'dino_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

### numpy.delete(arr, obj, axis=None)[source]

In [28]:
egg_box_copy = np.delete(egg_box, 2)

In [29]:
egg_box

array(['chicken_egg', 'country_egg', 'quail_egg', 'ostriches_egg'],
      dtype='<U13')

In [30]:
egg_box

array(['chicken_egg', 'country_egg', 'quail_egg', 'ostriches_egg'],
      dtype='<U13')

In [31]:
egg_box_copy

array(['chicken_egg', 'country_egg', 'ostriches_egg'], dtype='<U13')

### numpy.append(arr, values, axis=None)

In [32]:
egg_box

array(['chicken_egg', 'country_egg', 'quail_egg', 'ostriches_egg'],
      dtype='<U13')

In [33]:
egg_box_two

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

In [34]:
np.append(egg_box, 'duck_egg')

array(['chicken_egg', 'country_egg', 'quail_egg', 'ostriches_egg',
       'duck_egg'], dtype='<U13')

# Access array elements (Indexing, slicing)

In [35]:
egg_box 

array(['chicken_egg', 'country_egg', 'quail_egg', 'ostriches_egg'],
      dtype='<U13')

In [36]:
egg_box_two

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

In [37]:
egg_box_3

array([[['chicken_egg', 'country_egg', 'quail_egg'],
        ['chicken_egg', 'country_egg', 'quail_egg']],

       [['chicken_egg', 'country_egg', 'quail_egg'],
        ['chicken_egg', 'country_egg', 'quail_egg']]], dtype='<U11')

In [38]:
egg_box[-3]

'country_egg'

In [39]:
egg_box_two[1,1]

'country_egg'

In [40]:
egg_box_3[1,1,2]

'quail_egg'

## array[start : stop: step]

In [41]:
egg_box

array(['chicken_egg', 'country_egg', 'quail_egg', 'ostriches_egg'],
      dtype='<U13')

In [42]:
egg_box_two

array([['chicken_egg', 'country_egg', 'quail_egg'],
       ['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

In [43]:
egg_box[0:10:2]

array(['chicken_egg', 'quail_egg'], dtype='<U13')

In [44]:
egg_box_two[0:1]

array([['chicken_egg', 'country_egg', 'quail_egg']], dtype='<U11')

# Array reshape

### 1d to 2d

In [45]:
egg_box = np.append(egg_box, 'duck_egg')

In [46]:
egg_box.shape

(5,)

In [47]:
egg_box.reshape(2,2)

ValueError: cannot reshape array of size 5 into shape (2,2)

### 1d to 3d

In [ ]:
# egg_box.reshape(2,2,2)

In [ ]:
egg_box = np.array(['chicken_egg', 'country_egg', 'quail_egg', 'duck_egg', 'chicken_egg', 'country_egg', 'quail_egg', 'duck_egg'])

# Array iteration

In [ ]:
egg_box 

In [ ]:
egg_box_two

In [ ]:
for i in egg_box:
    print("I am ", i)

In [ ]:
for i in egg_box_two:
    for j in i:
        print("I am ", j)

In [ ]:
for i in np.nditer(egg_box_two):
    print("I am ", i)

In [ ]:
for idx, i in np.ndenumerate(egg_box_two):
    print("index", idx)
    print("I am ", i)

# Array joining

In [ ]:
egg_box_two

In [ ]:
egg_box_new = np.array([['egg1', 'egg2', 'egg3'],['egg4', 'egg5', 'egg6']])

In [ ]:
egg_box_new

### hstack - row

In [ ]:
np.hstack((egg_box_two, egg_box_new))

### vstack - column

In [ ]:
np.vstack((egg_box_two, egg_box_new))

### dstack

In [ ]:
np.dstack((egg_box_two, egg_box_new))

# Array splitting

In [ ]:
egg_box

In [ ]:
np.array_split(egg_box, 4)

#### hsplit(), vsplit(), dsplit() are also there

# Copy vs view

In [ ]:
egg_box_copy = egg_box.copy()
egg_box_view = egg_box.view()

In [ ]:
egg_box_copy

In [ ]:
egg_box

In [ ]:
egg_box_view[0] = 'duck_egg'

In [ ]:
egg_box_view

In [ ]:
egg_box

In [ ]:
egg_box_copy[1] = 'dino_egg'

In [ ]:
egg_box

In [ ]:
my_list = [1,2,3,4,5]
my_list + 1

In [ ]:
my_array = np.array([1,2,3,4,5])
my_array+1