In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/fish-dataset/fish dataset.csv


# importing libries

In [2]:
import pandas as pd

In [3]:
from sklearn.preprocessing import StandardScaler

In [4]:
from sklearn.preprocessing import MinMaxScaler

## Data

In [5]:
data = pd.read_csv('/kaggle/input/fish-dataset/fish dataset.csv')

In [6]:
data

Fish Name  Fish count
0     Gold Fish           7
1    Angel Fish          11
2     Glow Fish          13
3       Guppies          16
4  Rainbow Fish          18
5    Molly Fish          22
6        Tetra           24

## standardization

In [7]:
data.describe().round(2)

Fish count
count        7.00
mean        15.86
std          6.04
min          7.00
25%         12.00
50%         16.00
75%         20.00
max         24.00

In [8]:
data['Fish count'].values

array([ 7, 11, 13, 16, 18, 22, 24])

In [9]:
data['Fish count'].values.reshape(-1,1) # here we reshape to array in 2D array 

array([[ 7],
       [11],
       [13],
       [16],
       [18],
       [22],
       [24]])

In [10]:
scaler = StandardScaler()

In [11]:
standard_values = scaler.fit(data['Fish count'].values.reshape(-1,1))

In [12]:
standard_values

StandardScaler()

In [13]:
scaled_fish_count = scaler.transform(data['Fish count'].values.reshape(-1,1))

In [14]:
scaled_fish_count

array([[-1.584026  ],
       [-0.86865942],
       [-0.51097613],
       [ 0.02554881],
       [ 0.3832321 ],
       [ 1.09859868],
       [ 1.45628197]])

In [15]:
data['scaled fish count'] = scaled_fish_count

In [16]:
data.describe().round(2)

Fish count  scaled fish count
count        7.00               7.00
mean        15.86              -0.00
std          6.04               1.08
min          7.00              -1.58
25%         12.00              -0.69
50%         16.00               0.03
75%         20.00               0.74
max         24.00               1.46

## Normalization

In [17]:
scaler2 = MinMaxScaler() 

In [18]:
minmaxscaler = scaler2.fit(data['Fish count'].values.reshape(-1,1))

In [19]:
minmaxscaler

MinMaxScaler()

In [20]:
scaled_fish_count2 = scaler2.transform(data['Fish count'].values.reshape(-1,1))

In [21]:
scaled_fish_count2

array([[0.        ],
       [0.23529412],
       [0.35294118],
       [0.52941176],
       [0.64705882],
       [0.88235294],
       [1.        ]])

In [22]:
data['scaled fish count2'] = scaled_fish_count2

In [23]:
data.describe().round(2)

Fish count  scaled fish count  scaled fish count2
count        7.00               7.00                7.00
mean        15.86              -0.00                0.52
std          6.04               1.08                0.36
min          7.00              -1.58                0.00
25%         12.00              -0.69                0.29
50%         16.00               0.03                0.53
75%         20.00               0.74                0.76
max         24.00               1.46                1.00